name: 🐛 Bug Report
description: バグの報告用テンプレート
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## バグレポート
        バグを発見いただき、ありがとうございます。詳細な情報をご提供いただくことで、迅速な解決に繋がります。

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 バグの説明
      description: 発生しているバグについて詳しく説明してください
      placeholder: バグの内容を詳しく記述してください
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 再現手順
      description: バグを再現するための手順を記載してください
      placeholder: |
        1. '...'をクリック
        2. '...'を入力
        3. エラーが発生
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 期待される動作
      description: 本来期待される動作を記載してください
      placeholder: 正常な場合の動作を記述してください
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 実際の動作
      description: 実際に発生している動作を記載してください
      placeholder: 実際に起こった動作を記述してください
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 環境情報
      description: 発生環境の詳細情報
      placeholder: |
        - OS: [例: macOS 14.0]
        - ブラウザ: [例: Chrome 120.0]
        - バージョン: [例: v1.2.3]
        - その他の関連情報
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 追加情報
      description: スクリーンショット、ログ、その他の関連情報
      placeholder: スクリーンショット、エラーログ、関連するコードなど

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 優先度
      description: このバグの影響度を選択してください
      options:
        - 🔴 Critical - サービス停止・データ損失
        - 🟠 High - 主要機能に影響
        - 🟡 Medium - 軽微な機能影響
        - 🟢 Low - 表示崩れ・軽微な問題
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ チェックリスト
      description: 報告前の確認事項
      options:
        - label: 既存のIssueに同様の報告がないことを確認しました
          required: true
        - label: 再現手順を確認し、確実に再現できることを確認しました
          required: true
        - label: 環境情報を正確に記載しました
          required: true 