name: ✨ Feature Request
description: 新機能の要求用テンプレート
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能要求
        新しい機能のご提案をありがとうございます。詳細な情報をご提供いただくことで、より良い機能を開発できます。

  - type: textarea
    id: feature-summary
    attributes:
      label: 🎯 機能の概要
      description: 要求する機能の概要を簡潔に説明してください
      placeholder: 実装したい機能の概要を記述してください
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🔍 解決したい課題
      description: この機能によって解決されるべき課題や問題を説明してください
      placeholder: |
        現在のシステムで困っていることや、改善したい点を記述してください
        - 現状の問題点
        - 影響を受けるユーザー
        - 問題の頻度や重要度
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 提案する解決策
      description: 具体的にどのような機能や実装を提案しますか？
      placeholder: |
        具体的な解決策や実装案を記述してください
        - 機能の詳細
        - UI/UXの改善案
        - 技術的なアプローチ
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: 👤 ユーザーストーリー
      description: ユーザーの視点で機能を説明してください
      placeholder: |
        ユーザーとして、[何を]したいので、[なぜ]という機能が欲しい
        
        例:
        - 管理者として、ユーザーの行動ログを確認したいので、ダッシュボード機能が欲しい
        - 一般ユーザーとして、素早くデータを検索したいので、高速検索機能が欲しい
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ 受け入れ条件
      description: 機能が完成したと判断するための具体的な条件
      placeholder: |
        この機能が完成したと判断するための条件を箇条書きで記述してください
        - [ ] 条件1
        - [ ] 条件2
        - [ ] 条件3
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 代替案
      description: 他に考えられる解決策があれば記載してください
      placeholder: 提案した解決策以外に考えられる代替案があれば記述してください

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 追加情報
      description: 参考資料、モックアップ、関連するIssueなど
      placeholder: |
        関連する情報があれば記述してください
        - 参考サイトのURL
        - モックアップやスクリーンショット
        - 関連するIssueやPR

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 優先度
      description: この機能の重要度を選択してください
      options:
        - 🔴 Critical - ビジネスクリティカル
        - 🟠 High - 重要な機能改善
        - 🟡 Medium - 有用な機能追加
        - 🟢 Low - Nice to have
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: ⚙️ 実装複雑度（予想）
      description: 実装の難易度をどう予想しますか？
      options:
        - 🟢 Low - 軽微な変更
        - 🟡 Medium - 中程度の開発が必要
        - 🟠 High - 大きな設計変更が必要
        - 🔴 Very High - アーキテクチャレベルの変更
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ チェックリスト
      description: 提案前の確認事項
      options:
        - label: 既存のIssueに同様の提案がないことを確認しました
          required: true
        - label: 課題と解決策を明確に記載しました
          required: true
        - label: ユーザーストーリーと受け入れ条件を記載しました
          required: true 